import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BioArt</title>
        <meta name="description" content="Generated by create nft" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <section className={styles.wrapFirstBlock}>
          <div className={styles.firstBlock}>
            <div className={styles.firstBlockText}>
              <Image src="/icon_ba.svg" width={55} height={55} alt="icon" />
              <h3>BioArts</h3>
              <p>
                Artistic Transformation of
                <br /> Life into Information.
              </p>
              <span>Gold Hands</span>
              JHSASWHN-0001-20220101
            </div>
          </div>
        </section>
      </main>
      <section className={styles.slider}>
        <h2 style={{ textAlign: "center" }}>Popular NFTs</h2>
        <div className={styles.sliderWraper}>
          <button type="button" className={styles.sliderBtnPrev}></button>

          <div className={styles.bodySlider}>
            <div className={styles.itemSlider}>
              <div
                className={styles.itemSliderImage}
                style={{ backgroundImage: "url(/article-img.png)" }}
              />
              <span  style={{marginLeft: 15}}>
              <Image src="/icon_ba.svg" width={55} height={55} alt="icon" />
              </span>
              <p>BioArts</p>
              <p>Artistic Transformation of Life into Information.</p>
            </div>
            <div className={styles.itemSlider}>
              <div
                className={styles.itemSliderImage}
                style={{ backgroundImage: "url(/article-img.png)" }}
              />
              <span  style={{marginLeft: 15}}>
              <Image src="/icon_ba.svg" width={55} height={55} alt="icon" />
              </span>
              <p>BioArts</p>
              <p>Artistic Transformation of Life into Information.</p>
            </div>
            <div className={styles.itemSlider}>
              <div
                className={styles.itemSliderImage}
                style={{ backgroundImage: "url(/article-img.png)" }}
              />
              <span  style={{marginLeft: 15}}>
              <Image               
                src="/icon_facebook_b.png"
                width={55}
                height={55}
                alt="facebook"
              />
              </span>
              <p>BioArts</p>
              <p>Artistic Transformation of Life into Information.</p>
            </div>
          </div>
          <button type="button" className={styles.sliderBtnNext}></button>
        </div>
      </section>
    </div>
  );
}
